
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action CloseAction;
	
	private global::Gtk.Action PluginsAction;
	
	private global::Gtk.Action ReloadAction;
	
	private global::Gtk.VBox vbox3;
	
	private global::Gtk.MenuBar menubar2;
	
	private global::Gtk.HBox hbox3;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.CloseAction = new global::Gtk.Action ("CloseAction", global::Mono.Unix.Catalog.GetString ("Close"), null, null);
		this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
		w1.Add (this.CloseAction, null);
		this.PluginsAction = new global::Gtk.Action ("PluginsAction", global::Mono.Unix.Catalog.GetString ("Plugins"), null, null);
		this.PluginsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Plugins");
		w1.Add (this.PluginsAction, null);
		this.ReloadAction = new global::Gtk.Action ("ReloadAction", global::Mono.Unix.Catalog.GetString ("Reload"), null, null);
		this.ReloadAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Reload");
		w1.Add (this.ReloadAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='CloseAction' action='CloseAction'/></menu><menu name='PluginsAction' action='PluginsAction'><menuitem name='ReloadAction' action='ReloadAction'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox3.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 1;
		this.hbox3.BorderWidth = ((uint)(1));
		this.vbox3.Add (this.hbox3);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
		w3.Position = 1;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 533;
		this.DefaultHeight = 116;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.CloseAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
		this.ReloadAction.Activated += new global::System.EventHandler (this.OnReloadActionActivated);
	}
}
